title: Davids Blog
author: David
email: David@davidsserver.com
description: A place where I write about my experiences in IT, side projects, and anything else I find interesting!
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: David's Blog
  tagline: 
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  navigation:
    - title: Home
      url: "/"
  showPicker: false

  # generate social links in footer
  social_links:
    #github:  
    linkedIn: in/david-henry-9713aa1b2
    mail: David@davidsserver.com
    #rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

remote_theme: samarsault/texture